## NETWORK PARAMETERS
_OUTPUT_CLASSES = 8
_DIMENSION_EMBEDDINGS = 8
_DIMENSION_FC_INNERLAYERS = 16

## NETWORK TRAINING PARAMETERS
_TRAINING_EPOCHS = 150
_LR = 1e-3
_PATIENCE = 20
_BATCH_SIZE = 64
_GRAD_CLIP_VALUE = 1
